### PR TITLE
Initializing project

### PR DESCRIPTION
**Pull request by BeOff**
[**Link to the ticket**](https://trello.com/c/oaDixt4d/3-initialize-rails-5-project-with-postgresql-db-rspec-bootstrap)
**What it does:**
initializing project

### CODE REVIEW

**Comment by labs-ruby** [comment]
[I can not attach PR's from Trello's GitHub Power-Up](https://trello.com/c/FPQMhJL2/35-im-not-able-to-to-attach-prs-from-github-power-up)

**Comment by labs-ruby** [comment]
[Initialize Rails 5 project with PostgreSQL DB + RSpec + Bootstrap](https://trello.com/c/oaDixt4d/3-initialize-rails-5-project-with-postgresql-db-rspec-bootstrap)

**Comment by labs-ruby** [comment]
@BeOff since we're using RSpec, let's remove `test/*` folder completely

**Comment by BeOff** [comment]
Test comment.

**Comment by BeOff** [comment]
Test commit.

**Pull request merged**
